[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://riddlenote.du.r.appspot.com/api/:splat"
  status = 200
  force = true
  [[redirects.headers]]
    for = "/*"
    values = { X-Forwarded-Host = "riddlenote.com" }
    
